# Generated by Django 5.1.2 on 2024-12-09 23:38

import ventweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[ventweb.models.validar_rut], verbose_name='Rut'),
        ),
    ]
