# Generated by Django 5.1.2 on 2024-11-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventweb', '0002_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='usuario',
        ),
    ]
