# Generated by Django 5.1.2 on 2024-12-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventweb', '0003_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Rut'),
        ),
    ]
