# Generated by Django 5.1.2 on 2024-12-10 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventweb', '0004_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
